# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Multi-DRM"
  url = "https://pallycon.com/ko/multi-drm/"
  identifier = "multi-drm"
  weight = 10

[[main]]
  name = "License Service"
  url = "https://pallycon.com/ko/license-service/"
  parent = "multi-drm"
  weight = 11

[[main]]
  name = "Packaging"
  url = "https://pallycon.com/ko/packaging/"
  parent = "multi-drm"
  weight = 12

[[main]]
  name = "SDK"
  url = "https://pallycon.com/ko/sdk/"
  parent = "multi-drm"
  weight = 13

[[main]]
  name = "Anti Capture"
  url = "https://pallycon.com/ko/anti-capture/"
  parent = "multi-drm"
  weight = 14


[[main]]
  name = "Watermarking"
  url = "https://pallycon.com/ko/forensic-watermarking/"
  identifier = "watermarking"
  weight = 20

[[main]]
  name = "Forensic Watermarking"
  url = "https://pallycon.com/ko/forensic-watermarking/"
  parent = "watermarking"
  weight = 21

[[main]]
  name = "Visible Watermarking"
  url = "https://pallycon.com/ko/visible-watermarking/"
  parent = "watermarking"
  weight = 22


[[main]]
  name = "Developers"
  url = "https://pallycon.com/ko/drm-platform"
  identifier = "developer"
  weight = 30

[[main]]
  name = "DRM Platform"
  url = "https://pallycon.com/ko/drm-platform/"
  parent = "developer"
  weight = 31

[[main]]
  name = "Docs"
  url = "https://pallycon.com/docs/ko/"
  parent = "developer"
  weight = 32

[[main]]
  name = "Multi-DRM DEMO"
  url = "https://pallycon.com/ko/multi-drm-demo/"
  parent = "developer"
  weight = 33

[[main]]
  name = "Dev Console"
  url = "https://sample.pallycon.com/dev/devconsole/encDec.do?lang=ko"
  parent = "developer"
  weight = 34

[[main]]
  name = "HelpDesk"
  url = "https://pallycon.zendesk.com/hc/ko"
  parent = "developer"
  weight = 35


[[main]]
  name = "Blog"
  url = "https://pallycon.com/ko/blog/"
  weight = 40

[[main]]
  name = "Pricing"
  url = "https://pallycon.com/ko/pricing/"
  weight = 50

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50

[[main]]
  name = "Company"
  url = "https://pallycon.com/ko/about"
  identifier = "company"
  weight = 60

[[main]]
  name = "About"
  url = "https://pallycon.com/ko/about"
  parent = "company"
  weight = 61

[[main]]
  name = "Partners"
  url = "https://pallycon.com/ko/partners"
  parent = "company"
  weight = 62

[[main]]
  name = "Customers"
  url = "https://pallycon.com/ko/customers"
  parent = "company"
  weight = 63

[[main]]
  name = "Use Cases"
  url = "https://pallycon.com/ko/usecase"
  parent = "company"
  weight = 64

[[main]]
  name = "Contact"
  url = "https://pallycon.com/ko/contact"
  parent = "company"
  weight = 65

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
